import dotenv from "dotenv";

dotenv.config();

const { DISCORD_TOKEN, 
  DISCORD_CLIENT_ID,
  TARGET_USER_ROLES,
  WHITELISTED_CHANNELS,
  ALLOWED_ROLE_IDS,
  MOD_CHANNEL_ID,
  TWITCH_CLIENT_ID,
  TWITCH_CLIENT_SECRET,
  TWITCH_BROADCASTER,
  TWITCH_GLOBAL_DELAY
} = process.env;

if (!DISCORD_TOKEN || 
  !DISCORD_CLIENT_ID || 
  !WHITELISTED_CHANNELS||
  !ALLOWED_ROLE_IDS ||
  !MOD_CHANNEL_ID ||
  !TWITCH_CLIENT_ID ||
  !TWITCH_CLIENT_SECRET ||
  !TWITCH_BROADCASTER
) {
  throw new Error("Missing environment variables");
}

export const config = {
  DISCORD_TOKEN,
  DISCORD_CLIENT_ID,
  TARGET_USER_ROLES,
  WHITELISTED_CHANNELS,
  ALLOWED_ROLE_IDS,
  MOD_CHANNEL_ID,
  TWITCH_CLIENT_ID,
  TWITCH_CLIENT_SECRET,
  TWITCH_BROADCASTER,
  TWITCH_GLOBAL_DELAY
};